import { PrismaClient, PricingModel, Complexity, ToolStatus } from '@prisma/client';

const prisma = new PrismaClient();

// Top 50 Gen AI Consumer Web Products
const webAITools = [
  {
    name: "ChatGPT",
    slug: "chatgpt",
    description: "Advanced conversational AI assistant for text generation, coding, and problem-solving",
    category: "Conversational AI",
    subcategory: "Text Generation",
    pricingModel: PricingModel.FREEMIUM,
    pricingDetails: "Free tier available, Plus at $20/month",
    freeTier: true,
    startingPrice: 20,
    features: ["Text Generation", "Code Assistance", "Creative Writing", "Problem Solving"],
    useCases: ["Content Creation", "Programming Help", "Research", "Education"],
    complexity: Complexity.SIMPLE,
    targetAudience: ["General Users", "Developers", "Students", "Professionals"],
    website: "https://chat.openai.com",
    rating: 4.8,
    reviewCount: 15000,
    popularity: 100,
    isVerified: true,
    isTrending: true,
    isFeatured: true
  },
  {
    name: "DeepSeek",
    slug: "deepseek",
    description: "AI-powered code completion and programming assistant",
    category: "Development Tools",
    subcategory: "Code Generation",
    pricingModel: PricingModel.FREEMIUM,
    pricingDetails: "Free tier with premium features",
    freeTier: true,
    features: ["Code Completion", "Bug Detection", "Code Optimization"],
    useCases: ["Software Development", "Code Review", "Learning Programming"],
    complexity: Complexity.MODERATE,
    targetAudience: ["Developers", "Software Engineers"],
    website: "https://deepseek.com",
    rating: 4.6,
    reviewCount: 3200,
    popularity: 85,
    isVerified: true
  },
  {
    name: "Character.ai",
    slug: "character-ai",
    description: "Create and chat with AI characters for entertainment and roleplay",
    category: "Entertainment",
    subcategory: "Character Creation",
    pricingModel: PricingModel.FREEMIUM,
    pricingDetails: "Free with premium subscriptions available",
    freeTier: true,
    features: ["Character Creation", "Roleplay", "Interactive Conversations"],
    useCases: ["Entertainment", "Creative Writing", "Education"],
    complexity: Complexity.SIMPLE,
    targetAudience: ["General Users", "Writers", "Gamers"],
    website: "https://character.ai",
    rating: 4.4,
    reviewCount: 8500,
    popularity: 90,
    isVerified: true,
    isTrending: true
  },
  {
    name: "Perplexity",
    slug: "perplexity",
    description: "AI-powered search engine and research assistant",
    category: "Search & Research",
    subcategory: "Information Retrieval",
    pricingModel: PricingModel.FREEMIUM,
    pricingDetails: "Free searches with Pro subscription",
    freeTier: true,
    startingPrice: 20,
    features: ["AI Search", "Source Citations", "Research Assistance"],
    useCases: ["Research", "Fact-checking", "Academic Work"],
    complexity: Complexity.SIMPLE,
    targetAudience: ["Researchers", "Students", "Professionals"],
    website: "https://perplexity.ai",
    rating: 4.7,
    reviewCount: 5600,
    popularity: 88,
    isVerified: true,
    isTrending: true
  },
  {
    name: "JanitorAI",
    slug: "janitor-ai",
    description: "AI chatbot platform for character interactions and conversations",
    category: "Conversational AI",
    subcategory: "Character Chatbots",
    pricingModel: PricingModel.FREEMIUM,
    pricingDetails: "Free tier with premium features",
    freeTier: true,
    features: ["Character Chatbots", "Custom Personalities", "NSFW Content"],
    useCases: ["Entertainment", "Roleplay", "Creative Writing"],
    complexity: Complexity.SIMPLE,
    targetAudience: ["General Users", "Content Creators"],
    website: "https://janitorai.com",
    rating: 4.2,
    reviewCount: 4200,
    popularity: 75,
    isVerified: true
  },
  {
    name: "Claude",
    slug: "claude",
    description: "Anthropic's AI assistant for helpful, harmless, and honest conversations",
    category: "Conversational AI",
    subcategory: "AI Assistant",
    pricingModel: PricingModel.FREEMIUM,
    pricingDetails: "Free tier with Pro subscription",
    freeTier: true,
    startingPrice: 20,
    features: ["Text Analysis", "Code Generation", "Creative Writing", "Research"],
    useCases: ["Content Creation", "Analysis", "Programming", "Research"],
    complexity: Complexity.SIMPLE,
    targetAudience: ["Professionals", "Researchers", "Developers"],
    website: "https://claude.ai",
    rating: 4.8,
    reviewCount: 7800,
    popularity: 92,
    isVerified: true,
    isTrending: true
  },
  {
    name: "QuillBot",
    slug: "quillbot",
    description: "AI-powered paraphrasing and writing enhancement tool",
    category: "Writing Tools",
    subcategory: "Paraphrasing",
    pricingModel: PricingModel.FREEMIUM,
    pricingDetails: "Free tier with Premium subscription",
    freeTier: true,
    startingPrice: 9.95,
    features: ["Paraphrasing", "Grammar Check", "Plagiarism Detection", "Citation Generator"],
    useCases: ["Academic Writing", "Content Creation", "Editing"],
    complexity: Complexity.SIMPLE,
    targetAudience: ["Students", "Writers", "Researchers"],
    website: "https://quillbot.com",
    rating: 4.5,
    reviewCount: 12000,
    popularity: 85,
    isVerified: true
  },
  {
    name: "SUNO",
    slug: "suno",
    description: "AI music generation platform for creating songs and audio",
    category: "Audio & Music",
    subcategory: "Music Generation",
    pricingModel: PricingModel.FREEMIUM,
    pricingDetails: "Free credits with subscription plans",
    freeTier: true,
    startingPrice: 10,
    features: ["Music Generation", "Lyrics Creation", "Audio Production"],
    useCases: ["Music Creation", "Content Production", "Entertainment"],
    complexity: Complexity.SIMPLE,
    targetAudience: ["Musicians", "Content Creators", "Hobbyists"],
    website: "https://suno.ai",
    rating: 4.6,
    reviewCount: 3800,
    popularity: 80,
    isVerified: true,
    isTrending: true
  },
  {
    name: "Midjourney",
    slug: "midjourney",
    description: "AI image generation platform for creating stunning artwork",
    category: "Image Generation",
    subcategory: "AI Art",
    pricingModel: PricingModel.SUBSCRIPTION,
    pricingDetails: "Subscription plans starting at $10/month",
    freeTier: false,
    startingPrice: 10,
    features: ["Image Generation", "Art Creation", "Style Transfer", "High Resolution"],
    useCases: ["Digital Art", "Concept Design", "Marketing Materials", "Creative Projects"],
    complexity: Complexity.MODERATE,
    targetAudience: ["Artists", "Designers", "Content Creators"],
    website: "https://midjourney.com",
    rating: 4.7,
    reviewCount: 18000,
    popularity: 95,
    isVerified: true,
    isTrending: true,
    isFeatured: true
  },
  {
    name: "Gamma",
    slug: "gamma",
    description: "AI-powered presentation and document creation platform",
    category: "Productivity",
    subcategory: "Presentation Tools",
    pricingModel: PricingModel.FREEMIUM,
    pricingDetails: "Free tier with Pro subscriptions",
    freeTier: true,
    startingPrice: 8,
    features: ["AI Presentations", "Document Creation", "Design Templates", "Collaboration"],
    useCases: ["Business Presentations", "Educational Content", "Marketing Materials"],
    complexity: Complexity.SIMPLE,
    targetAudience: ["Business Professionals", "Educators", "Students"],
    website: "https://gamma.app",
    rating: 4.6,
    reviewCount: 5400,
    popularity: 78,
    isVerified: true,
    isTrending: true
  },
  {
    name: "Canva",
    slug: "canva",
    description: "Design platform with AI-powered features for graphics and content",
    category: "Design Tools",
    subcategory: "Graphic Design",
    pricingModel: PricingModel.FREEMIUM,
    pricingDetails: "Free tier with Pro and Teams plans",
    freeTier: true,
    startingPrice: 12.99,
    features: ["Graphic Design", "AI Image Generation", "Templates", "Brand Kit"],
    useCases: ["Social Media Graphics", "Marketing Materials", "Presentations", "Print Design"],
    complexity: Complexity.SIMPLE,
    targetAudience: ["Marketers", "Small Businesses", "Content Creators", "Students"],
    website: "https://canva.com",
    rating: 4.8,
    reviewCount: 45000,
    popularity: 98,
    isVerified: true,
    isFeatured: true
  }
];

// Top 50 Gen AI Consumer Mobile Apps
const mobileAITools = [
  {
    name: "NOVA AI Chatbot",
    slug: "nova-ai-chatbot",
    description: "Advanced AI chatbot mobile application",
    category: "Conversational AI",
    subcategory: "Mobile Chatbot",
    pricingModel: PricingModel.FREEMIUM,
    pricingDetails: "Free with in-app purchases",
    freeTier: true,
    mobileApp: true,
    features: ["Mobile Chat", "Voice Input", "Offline Mode"],
    useCases: ["Mobile Assistance", "Quick Queries", "On-the-go Help"],
    complexity: Complexity.SIMPLE,
    targetAudience: ["Mobile Users", "General Public"],
    website: "https://nova-ai.app",
    rating: 4.5,
    reviewCount: 8500,
    popularity: 85,
    isVerified: true
  },
  {
    name: "Microsoft Edge",
    slug: "microsoft-edge-mobile",
    description: "Microsoft's browser with integrated AI features",
    category: "Browsers",
    subcategory: "AI-Enhanced Browser",
    pricingModel: PricingModel.FREE,
    pricingDetails: "Free to use",
    freeTier: true,
    mobileApp: true,
    features: ["AI Search", "Copilot Integration", "Smart Browsing"],
    useCases: ["Web Browsing", "AI Search", "Productivity"],
    complexity: Complexity.SIMPLE,
    targetAudience: ["General Users", "Professionals"],
    website: "https://microsoft.com/edge",
    rating: 4.3,
    reviewCount: 15000,
    popularity: 90,
    isVerified: true
  },
  {
    name: "Baidu AI Search",
    slug: "baidu-ai-search",
    description: "Baidu's AI-powered search application",
    category: "Search & Research",
    subcategory: "Mobile Search",
    pricingModel: PricingModel.FREE,
    pricingDetails: "Free to use",
    freeTier: true,
    mobileApp: true,
    features: ["AI Search", "Voice Search", "Image Recognition"],
    useCases: ["Search", "Information Retrieval", "Voice Queries"],
    complexity: Complexity.SIMPLE,
    targetAudience: ["Chinese Users", "General Public"],
    website: "https://baidu.com",
    rating: 4.2,
    reviewCount: 12000,
    popularity: 80,
    isVerified: true,
    isRegionSpecific: "China"
  },
  {
    name: "PhotoMath",
    slug: "photomath",
    description: "AI-powered math problem solver using camera",
    category: "Education",
    subcategory: "Math Solver",
    pricingModel: PricingModel.FREEMIUM,
    pricingDetails: "Free with premium features",
    freeTier: true,
    mobileApp: true,
    features: ["Math Problem Solving", "Step-by-step Solutions", "Camera Recognition"],
    useCases: ["Education", "Homework Help", "Math Learning"],
    complexity: Complexity.SIMPLE,
    targetAudience: ["Students", "Teachers", "Parents"],
    website: "https://photomath.com",
    rating: 4.7,
    reviewCount: 25000,
    popularity: 95,
    isVerified: true,
    isFeatured: true
  },
  {
    name: "Quark AI Assistant",
    slug: "quark-ai-assistant",
    description: "Comprehensive AI assistant mobile app",
    category: "Productivity",
    subcategory: "AI Assistant",
    pricingModel: PricingModel.FREEMIUM,
    pricingDetails: "Free tier with premium subscriptions",
    freeTier: true,
    mobileApp: true,
    features: ["Task Management", "AI Chat", "Productivity Tools"],
    useCases: ["Productivity", "Task Management", "Personal Assistant"],
    complexity: Complexity.SIMPLE,
    targetAudience: ["Professionals", "Students", "General Users"],
    website: "https://quark.ai",
    rating: 4.4,
    reviewCount: 6800,
    popularity: 75,
    isVerified: true
  },
  {
    name: "Talkie",
    slug: "talkie-mobile",
    description: "AI character chat and roleplay mobile app",
    category: "Entertainment",
    subcategory: "Character Chat",
    pricingModel: PricingModel.FREEMIUM,
    pricingDetails: "Free with in-app purchases",
    freeTier: true,
    mobileApp: true,
    features: ["Character Creation", "Roleplay", "Voice Chat"],
    useCases: ["Entertainment", "Roleplay", "Social Interaction"],
    complexity: Complexity.SIMPLE,
    targetAudience: ["Entertainment Seekers", "Gamers"],
    website: "https://talkie.ai",
    rating: 4.3,
    reviewCount: 9200,
    popularity: 80,
    isVerified: true
  },
  {
    name: "Remini",
    slug: "remini",
    description: "AI photo enhancer and upscaler mobile app",
    category: "Photo & Video",
    subcategory: "Photo Enhancement",
    pricingModel: PricingModel.FREEMIUM,
    pricingDetails: "Free with premium subscriptions",
    freeTier: true,
    mobileApp: true,
    features: ["Photo Enhancement", "AI Upscaling", "Face Enhancement"],
    useCases: ["Photo Editing", "Image Enhancement", "Social Media"],
    complexity: Complexity.SIMPLE,
    targetAudience: ["Photo Enthusiasts", "Social Media Users"],
    website: "https://remini.ai",
    rating: 4.6,
    reviewCount: 18000,
    popularity: 90,
    isVerified: true,
    isTrending: true
  },
  {
    name: "VivaCut",
    slug: "vivacut",
    description: "AI-powered video editing mobile application",
    category: "Video & Media",
    subcategory: "Video Editing",
    pricingModel: PricingModel.FREEMIUM,
    pricingDetails: "Free with premium features",
    freeTier: true,
    mobileApp: true,
    features: ["Video Editing", "AI Effects", "Template Library"],
    useCases: ["Video Editing", "Content Creation", "Social Media"],
    complexity: Complexity.MODERATE,
    targetAudience: ["Content Creators", "Video Editors"],
    website: "https://vivacut.app",
    rating: 4.5,
    reviewCount: 12500,
    popularity: 85,
    isVerified: true
  },
  {
    name: "Chatbot AI Search Assistant",
    slug: "chatbot-ai-search-assistant",
    description: "Mobile AI search and chat assistant",
    category: "Conversational AI",
    subcategory: "Search Assistant",
    pricingModel: PricingModel.FREEMIUM,
    pricingDetails: "Free with premium features",
    freeTier: true,
    mobileApp: true,
    features: ["AI Search", "Chat Interface", "Voice Commands"],
    useCases: ["Search", "Information Retrieval", "Quick Answers"],
    complexity: Complexity.SIMPLE,
    targetAudience: ["General Users", "Mobile Users"],
    website: "https://chatbot-search.app",
    rating: 4.2,
    reviewCount: 5600,
    popularity: 70,
    isVerified: true
  },
  {
    name: "Mertu",
    slug: "mertu",
    description: "AI-powered social networking and chat app",
    category: "Social Media",
    subcategory: "AI Social",
    pricingModel: PricingModel.FREEMIUM,
    pricingDetails: "Free with premium features",
    freeTier: true,
    mobileApp: true,
    features: ["AI Chat", "Social Networking", "Smart Matching"],
    useCases: ["Social Networking", "AI Conversations", "Meeting People"],
    complexity: Complexity.SIMPLE,
    targetAudience: ["Social Media Users", "Young Adults"],
    website: "https://mertu.app",
    rating: 4.1,
    reviewCount: 3400,
    popularity: 60,
    isVerified: true
  },
  {
    name: "FaceApp",
    slug: "faceapp",
    description: "AI-powered face editing and transformation app",
    category: "Photo & Video",
    subcategory: "Face Editing",
    pricingModel: PricingModel.FREEMIUM,
    pricingDetails: "Free with premium subscriptions",
    freeTier: true,
    mobileApp: true,
    features: ["Face Transformation", "Age Progression", "Gender Swap", "Style Transfer"],
    useCases: ["Photo Editing", "Entertainment", "Social Media"],
    complexity: Complexity.SIMPLE,
    targetAudience: ["Social Media Users", "Photo Enthusiasts"],
    website: "https://faceapp.com",
    rating: 4.4,
    reviewCount: 22000,
    popularity: 88,
    isVerified: true
  },
  {
    name: "Filmora",
    slug: "filmora-mobile",
    description: "AI-enhanced video editing mobile app",
    category: "Video & Media",
    subcategory: "Video Editing",
    pricingModel: PricingModel.FREEMIUM,
    pricingDetails: "Free with watermark, premium subscriptions available",
    freeTier: true,
    mobileApp: true,
    features: ["Video Editing", "AI Effects", "Music Library", "Templates"],
    useCases: ["Video Creation", "Content Production", "Social Media"],
    complexity: Complexity.MODERATE,
    targetAudience: ["Content Creators", "Video Editors", "Social Media Users"],
    website: "https://filmora.wondershare.com",
    rating: 4.5,
    reviewCount: 16000,
    popularity: 82,
    isVerified: true
  },
  {
    name: "BeautyPlus",
    slug: "beautyplus",
    description: "AI-powered beauty camera and photo editor",
    category: "Photo & Video",
    subcategory: "Beauty Camera",
    pricingModel: PricingModel.FREEMIUM,
    pricingDetails: "Free with premium features",
    freeTier: true,
    mobileApp: true,
    features: ["Beauty Filters", "Makeup Effects", "Body Editing", "Background Removal"],
    useCases: ["Selfie Enhancement", "Beauty Photography", "Social Media"],
    complexity: Complexity.SIMPLE,
    targetAudience: ["Beauty Enthusiasts", "Social Media Users", "Photographers"],
    website: "https://beautyplus.com",
    rating: 4.3,
    reviewCount: 28000,
    popularity: 85,
    isVerified: true
  },
  {
    name: "Lensa AI",
    slug: "lensa-ai",
    description: "AI-powered photo editing and avatar creation app",
    category: "Photo & Video",
    subcategory: "AI Avatars",
    pricingModel: PricingModel.FREEMIUM,
    pricingDetails: "Free with premium features for AI avatars",
    freeTier: true,
    mobileApp: true,
    features: ["AI Avatars", "Photo Enhancement", "Background Removal", "Portrait Editing"],
    useCases: ["Avatar Creation", "Photo Editing", "Social Media", "Profile Pictures"],
    complexity: Complexity.SIMPLE,
    targetAudience: ["Social Media Users", "Content Creators", "General Public"],
    website: "https://prisma-ai.com/lensa",
    rating: 4.3,
    reviewCount: 16500,
    popularity: 82,
    isVerified: true,
    isTrending: true
  }
];

async function seedAITools() {
  console.log('Starting to seed AI tools database...');

  try {
    // Combine both lists
    const allTools = [...webAITools, ...mobileAITools];
    
    console.log(`Preparing to add ${allTools.length} AI tools...`);

    for (const tool of allTools) {
      try {
        // Check if tool already exists
        const existingTool = await prisma.aITool.findUnique({
          where: { slug: tool.slug }
        });

        if (existingTool) {
          console.log(`Tool ${tool.name} already exists, skipping...`);
          continue;
        }

        // Create the tool
        await prisma.aITool.create({
          data: {
            ...tool,
            status: ToolStatus.ACTIVE,
            addedBy: 'system-seed',
            verifiedBy: 'system-seed'
          }
        });

        console.log(`✅ Added ${tool.name}`);
      } catch (error) {
        console.error(`❌ Error adding ${tool.name}:`, error);
      }
    }

    console.log('✅ AI tools seeding completed!');
    
    // Print summary
    const totalTools = await prisma.aITool.count();
    console.log(`📊 Total AI tools in database: ${totalTools}`);

  } catch (error) {
    console.error('❌ Error during seeding:', error);
  } finally {
    await prisma.$disconnect();
  }
}

// Run the seed function
seedAITools(); 